name: Terraform CI/CD

on:
  push:
    branches:
      - cicd-with-gke
  pull_request:
    branches:
      - cicd-with-gke

env:
  TF_VERSION: 1.6.6
  TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_region: asia-south1
  TF_VAR_zone: asia-south1-a

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      # Setup gcloud
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # Terraform Apply (Push to cicd-with-gke only) 
      - name: Terraform Apply 
        if: github.ref == 'refs/heads/cicd-with-gke' && github.event_name == 'push' 
        run: terraform apply -auto-approve -input=false

      # Terraform Destroy (Runs on push to cicd-with-gke)
      #- name: Terraform Destroy
        #if: github.ref == 'refs/heads/cicd-with-gke' && github.event_name == 'push'
        #run: terraform destroy -auto-approve -input=false
